export const GET_HOME = "GET_HOME";
export const GET_HOME_SUCCESS = "GET_HOME_SUCCESS";
export const GET_HOME_FAILURE = "GET_HOME_FAILURE";

export const GET_TVSHOWS = "GET_TVSHOWS";
export const GET_TVSHOWS_SUCCESS = "GET_TVSHOWS_SUCCESS";
export const GET_TVSHOWS_FAILURE = "GET_TVSHOWS_FAILURE";

export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";

export const GET_NEWANDPOPULAR = "GET_NEWANDPOPULAR";
export const GET_NEWANDPOPULAR_SUCCESS = "GET_NEWANDPOPULAR_SUCCESS";
export const GET_NEWANDPOPULAR_FAILURE = "GET_NEWANDPOPULAR_FAILURE";

export const GET_MYLIST = "GET_MYLIST";
export const GET_MYLIST_SUCCESS = "GET_MYLIST_SUCCESS";
export const GET_MYLIST_FAILURE = "GET_MYLIST_FAILURE";
